### PR TITLE
Integration tests for the extension

### LINKED ISSUE #15: Extension tests that make sure live reload works
We should have some tests that verify live reload of .rock files work. See https://github.com/quarkiverse/quarkus-pact/blob/main/quarkus-pact-consumer/integration-tests/src/test/java/io/quarkiverse/pact/it/DevModeContractTestIT.java for an example.

### PR DESCRIPTION
**Pull request by holly-cummins**
This adds tests which ensure applications using the extension work as expected in a normal `mvn verify`, and in dev mode, and that hot reload triggers recompile. It will fail until #10 is merged.

Resolves #15

### CODE REVIEW

**Comment by holly-cummins** [comment]
Darn. These tests are passing in the build, and they should not be passing if run without #10. Will investigate.

**Comment by hannotify** [comment]
So I rebased this branch on `main` to have it work together with the fix for #10. But the `SimpleHelloWorldTest` is still failing when running a `mvn verify` from the root dir. However, if I run `SimpleHelloWorldTest` on its own (or from the `simple-app` directory) it succeeds. 

@holly-cummins: does it even make sense to run `SimpleHelloWorldTest` from the root dir of the project? Or could we safely ignore it?

**Comment by holly-cummins** [comment]
Hmm, interesting. The integration tests should pass when run from the root dir of the project; the idea is that you get the faster feedback about the behaviour of the extension, without having to go separately try things out in a test app. The tests passed for me last week, and I've just rebased, and they still pass. But I can see they're failing in the CI, and also failing for you, @hannotify, so something must be off. I will investigate.

**Comment by holly-cummins** [comment]
Ok, this should now be working in the CI, @hannotify. I think there may have been two separate issues

I was able to reproduce locally by deleting `~/.m2/repository/org/example` and then running a `mvn install` without `clean`. That gave a `wrong name` error. 

I was working on fixing that, and then I noticed that the CI error was actually about class versions (but I had to scroll waaaay up to find it). So I've reinstated a version for the maven compiler plugin. I think I perhaps took it out to tidy an IDE warning, which was apparently unwise. With that, the CI is passing. 

For running locally, I think the trick is that if you get `wrong name` error, adding `clean` to the build command will sort it out. It's not ideal, but it should work.

**Comment by hannotify** [comment]
Excellent @holly-cummins, that is good news!

And I can confirm that the build succeeds locally when I run `mvn clean verify`. So I'll happily merge this PR!

**Pull request merged**
