### PR TITLE
Implement a better rock score

### LINKED ISSUE #60: Implement a better rock score
Ideas for a better rock score:

* Curate a list of the best known (or the most popular) 80's rock songs.
* Build a list of the most common nouns in these songs.
* Assign a certain number of points to these nouns (the more common, the more points)
* Sum these points for each Rockstar program.
* Divide the sum by the sum of points for the top performing 80's rock song.
* Multiply by 100 and round to integer to get to the final score.
* Make sure the score can't get below `0` or above `100`.

### PR DESCRIPTION
**Pull request by hannotify**
Closes #60.

The rock score is calculated based on the frequency of words that appear in a selection of popular 80's rock songs. If the rockstar program contains as many high-scoring words (or more!) as the highest scoring 80's rock song, a rock score of `100` is assigned. If it doesn't contain any scoring words, the rock score is `0`.

### CODE REVIEW

**Comment by hannotify** [comment]
Hmm... I see some tests are failing when run with Maven. They're successful when run directly from the IDE, though. I'll have to look into that. I'm afraid my time for today is up, so I'll check it out tomorrow first thing in the morning.

**Comment by hannotify** [comment]
I've been looking at this for a while now, but I don't have a clue how to fix the remaining failing `DevModeRockstarExtensionIT`. I'll commit what I have done so far and I'm hoping we can get it sorted next time we meet. 🤞🏻

**Comment by hannotify** [comment]
I completed the lyrics fetching. I'm proud to say I used Structured Concurrency to the max. 😄 

I still need to change the existing classes (`RockScoreCalculator`, `WordCounter` and `LyricsRatingCalculator`) so they'll use the downloaded lyrics instead of those currently in the repo. Will probably get to that tomorrow.

**Review by holly-cummins — APPROVED** [review]

**Comment by hannotify** [comment]
I ended up replacing structured concurrency with an oldschool ExecutorService, to prevent preview warnings spreading across all JVMs that we use in our setup.

Besides, the previous solution required the app developer to also add the `--enable-preview` flag to their pom.xml.
Replacing it with a completed feature makes their user experience a bit better.

**Pull request merged**
